// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback to a dummy URL during build (when env var is missing)
    // This allows 'prisma generate' to succeed in the Dockerfile.
    url: process.env["DATABASE_URL"] || "postgresql://dummy:dummy@localhost:5432/dummy",
  },
});
